apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Shweta-bit/infrastructure.git
    targetRevision: HEAD
    path: aws-load-balancer-controller
    helm:
      parameters:
        - name: vpcId
          value: vpc-0e3c6b2b9ca88015e
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
