apiVersion: v1
kind: Service
metadata:
  name: myapp1-nodeport-service
spec:
  type: NodePort  # Regular k8s Service manifest with type as LoadBalancer
  selector:
    app: myapp1    
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 31280