apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: filebeat
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Shweta-bit/infrastructure.git
    targetRevision: HEAD
    path: filebeat
  destination:
    server: https://kubernetes.default.svc
    namespace: logging